apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-permission-update-pv-{{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.nfs.storage | default "5Gi" }}
  accessModes:
  - ReadWriteMany
  nfs: 
    path: {{ .Values.nfs.path | default "/" }}
    server: {{ required ".nfs.host is required " .Values.nfs.host  }}
