{{- if .Values.podSecurityPolicy.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - privileged-{{ .Release.Namespace }}-{{ .Release.Name }}
{{- end -}}
