# A helm example values file for migrating a CloudBees CI for Modern Platform install
# Install an nginx-ingress controller
nginx-ingress:
  # Change this to true, if you want to install the NGINX Ingress Controller
  Enabled: false

OperationsCenter:
  # Set the HostName for the Operation Center
  HostName: 'cloudbees-core.example.com'
  ContextPath: null
  Ingress:
    tls:
    ## Set this to true in order to enable TLS on the ingress record
      Enable: false
      SecretName: core-example-com-tls
      Host: jenkins.cluster.local

# Do not change these values. They are all set for migrating CloudBees CI. 
Persistence:
  ExistingClaim: 'jenkins-home-cjoc-0' 
