# A helm example values file for migrating a CloudBees Core for Modern Platfrom Install for OpenShift.
# Install an nginx-ingress controller
nginx-ingress:
  Enabled: false
OperationsCenter:
  # Set the platform to openshift, so that routes are created
  Platform: 'openshift'
  # Set the HostName for the Operation Center
  HostName: 'cloudbees-core.example.com'
  ContextPath: null
  Ingress:
    tls:
    ## Set this to true in order to enable TLS on the ingress route
      Enable: false
      ## Replace with your Kubernetes Certificate Select
      SecretName: core-example-com-tls
      Host: jenkins.cluster.local
    # Update this with the openshift project your are using.
    Project:
      name: myproject

# Do not change these values. They are all set for migrating CloudBees Core.
Persistence:
  ExistingClaim: 'jenkins-home-cjoc-0'

